# Generated by Django 4.2.4 on 2023-09-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppF', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parentesco',
        ),
        migrations.AddField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
