# Generated by Django 4.2.4 on 2023-09-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppF', '0002_delete_parentesco_familiar_parentesco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='dni',
        ),
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
